### ISSUE TITLE
Alternate instructions for Ubuntu 

### ISSUE THREAD

**Issue by shaunagm** [zrrobbins/openedxstats#19]
Running the current install process on Ubuntu (& likely Debian, maybe other Linux distros) does not correctly install postgresql, and gives me the error: "pg_ctl: command not found"

I uninstalled postgresql via homebrew and tried [these alternative instructions](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-postgresql-on-ubuntu-14-04):

    sudo apt-get update
    sudo apt-get install postgresql postgresql-contrib
    sudo -i -u postgres

Then, to start the server:

    /etc/init.d/postgresql start

However I run into an error: 

    django.db.utils.OperationalError: FATAL:  Peer authentication failed for user "postgres"

Not sure how precisely to split up the instructions here - perhaps just leave a note when telling people to install brew *not* to do so if you're on Ubuntu.  You say that skipping that step will cause the requirements.txt install to fail, but it may be fine if you install [this missing dependency](https://github.com/zrrobbins/openedxstats/issues/17)?

**Comment by zrrobbins** [comment]
Sounds good, I'll go over the setup procedure and make it more linux friendly. In the meantime this fix might help you: http://stackoverflow.com/questions/18664074/getting-error-peer-authentication-failed-for-user-postgres-when-trying-to-ge

**Comment by shaunagm** [comment]
The steps for Linux seem to be:

* get the code, make a virtualenv, run virtualenv (however you do it)
* run requirements.txt with the addition of libpq-dev
* install postgresql via apt-get (sudo apt-get update, sudo apt-get install postgresql postgresql-contrib)
* start server (/etc/init.d/postgresql start)
* create database by logging in (psql -U postgres) and running command (create database openedxstats;)
* open up /etc/postgresql/9.5/main/pg_hba.conf and change "local   all    postgres     peer" to "local   all postgres trust" then restart the service (sudo service postgresql restart )

This gets us at least to the "run" section of the instructions, and "python manage.py runserver" does indeed run, but we still get connection issues:

>   File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
[26/Jul/2016 13:42:43] "GET /login/ HTTP/1.1" 500 59

**Comment by shaunagm** [comment]
Most of that traceback was because I don't have an email backend configured on my computer (see [here](http://stackoverflow.com/questions/38314365/mail-admins-causing-connection-refused-for-django-apache2) but the 500 error is still an issue.

**Comment by zrrobbins** [comment]
Addressed in most recent docs update
